name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: your_mysql_password
          MYSQL_DATABASE: blog_db
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3307:3306

    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmysqlclient-dev python3-dev

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Django checks
        run: |
          python3 blog_project/manage.py check

      - name: Run Tests
        run: |
          python3 blog_project/manage.py test blog
